### ISSUE TITLE
安装后没有反应

### ISSUE THREAD

**Issue by stephen-v** [knightli/markdown-assistant#5]
Markdown Assistant 0.1.0
qiniu-uploader 0.0.3
atom:1.3.2
安装后没有反应，请问哪里可以看到日志不？

**Comment by AllinZzz** [comment]
安装后，qiniu-uploader ，没有设置settings 按钮，没法设置

![image](https://cloud.githubusercontent.com/assets/13101999/26483020/5e8186b0-421d-11e7-975d-327dcedc1174.png)

**Comment by AllinZzz** [comment]
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Object.<anonymous> (C:\Users\zengyaoliang\.atom\packages\qiniu-uploader\node_modules\sync-request\index.js:10:1)
    at Module.get_Module._compile (D:\Atomx64\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (D:\Atomx64\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///D:/Atomx64/resources/app/static/index.js:47:45)
    at require (D:\Atomx64\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (C:\Users\zengyaoliang\.atom\packages\qiniu-uploader\node_modules\qiniu\qiniu\zone.js:1:94)
    at Module.get_Module._compile (D:\Atomx64\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (D:\Atomx64\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///D:/Atomx64/resources/app/static/index.js:47:45)
    at require (D:\Atomx64\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (C:\Users\zengyaoliang\.atom\packages\qiniu-uploader\node_modules\qiniu\qiniu\io.js:11:12)
    at Module.get_Module._compile (D:\Atomx64\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (D:\Atomx64\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///D:/Atomx64/resources/app/static/index.js:47:45)
    at require (D:\Atomx64\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (C:\Users\zengyaoliang\.atom\packages\qiniu-uploader\node_modules\qiniu\index.js:8:7)
    at Module.get_Module._compile (D:\Atomx64\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (D:\Atomx64\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///D:/Atomx64/resources/app/static/index.js:47:45)
    at require (D:\Atomx64\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (file:///C:/Users/zengyaoliang/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:9)
    at Object.<anonymous> (file:///C:/Users/zengyaoliang/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:1)
    at Module.get_Module._compile (D:\Atomx64\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .coffee] (D:\Atomx64\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///D:/Atomx64/resources/app/static/index.js:47:45)
    at require (D:\Atomx64\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (file:///C:/Users/zengyaoliang/.atom/packages/qiniu-uploader/lib/main.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/zengyaoliang/.atom/packages/qiniu-uploader/lib/main.coffee:1:1)
    at Module.get_Module._compile (D:\Atomx64\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .coffee] (D:\Atomx64\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///D:/Atomx64/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (D:\Atomx64\resources\app\static\<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (D:\Atomx64\resources\app\src\package.js:887:1)
    at Package.module.exports.Package.activateConfig (D:\Atomx64\resources\app\src\package.js:301:1)
    at PackageManager.module.exports.PackageManager.packageHasSettings (D:\Atomx64\resources\app\node_modules\settings-view\lib\package-manager.js:68:1)
    at PackageCard.hasSettings (D:\Atomx64\resources\app\node_modules\settings-view\lib\package-card.js:793:1)
    at PackageCard.updateSettingsState (D:\Atomx64\resources\app\node_modules\settings-view\lib\package-card.js:438:1)
    at PackageCard.updateInterfaceState (D:\Atomx64\resources\app\node_modules\settings-view\lib\package-card.js:430:1)
    at D:\Atomx64\resources\app\node_modules\settings-view\lib\package-card.js:727:1
    at D:\Atomx64\resources\app\node_modules\settings-view\lib\package-card.js:810:1
    at Function.module.exports.Emitter.simpleDispatch (D:\Atomx64\resources\app\node_modules\event-kit\lib\emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (D:\Atomx64\resources\app\node_modules\event-kit\lib\emitter.js:141:1)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (D:\Atomx64\resources\app\node_modules\settings-view\lib\package-manager.js:687:1)
    at D:\Atomx64\resources\app\node_modules\settings-view\lib\package-manager.js:526:1
    at exit (D:\Atomx64\resources\app\node_modules\settings-view\lib\package-manager.js:128:1)
    at triggerExitCallback (D:\Atomx64\resources\app\src\buffered-process.js:338:1)
    at ChildProcess.<anonymous> (D:\Atomx64\resources\app\src\buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
